---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-2
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./cluster/app-02
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: app-02
  patches:
  - patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: app-02
      spec:
        minReplicas: 2             
    target:
      name: app-02
      kind: HorizontalPodAutoscaler
  targetNamespace: default
  timeout: 3m0s
  wait: true
