---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./cluster
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: podinfo
  patches:
  - patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: simple-app
      spec:
        minReplicas: 1             
    target:
      name: simple-app
      kind: HorizontalPodAutoscaler
  targetNamespace: default
  timeout: 3m0s
  wait: true
